application:
  knowledge graph

resource:
  gpus: [0]
  cpu_per_gpu: 8
  dim: 512

graph:
  file_name: <math.train>

build:
  optimizer:
    type: Adam
    lr: 5.0e-3
    weight_decay: 0
  num_partition: auto
  num_negative: 8
  batch_size: 100000
  episode_size: 100

train:
  model: RotatE
  num_epoch: 2000
  margin: 9
  sample_batch_size: 2000
  adversarial_temperature: 2
  log_frequency: 100

evaluate:
  task: link prediction
  file_name: <math.test>
  filter_files:
    - <math.train>
    - <math.valid>
    - <math.test>
  target: tail

save:
  file_name: rotate_math.pkl