application:
  knowledge graph

resource:
  gpus: []
  cpu_per_gpu: auto
  dim: 1024

graph:
  file_name: <wn18.train>

build:
  optimizer:
    type: Adam
    lr: 5.0e-6
    weight_decay: 0
  num_partition: auto
  num_negative: 64
  batch_size: 100000
  episode_size: 1

train:
  model: RotatE
  num_epoch: 4000
  margin: 9
  sample_batch_size: 2000
  adversarial_temperature: 2
  log_frequency: 100

evaluate:
  task: link prediction
  file_name: <wn18.test>
  filter_files:
    - <wn18.train>
    - <wn18.valid>
    - <wn18.test>
  # fast_mode: 3000

save:
  file_name: rotate_wn18.pkl